In [2]:
import pandas as pd
s1 = pd.Series([1,2,3,4,5])
s2 =pd.Series([6,7,8,9,10])
df= pd.DataFrame({'a':s1,'b':s2})

#关于数据导入 数据处理（类型的修改，分箱）等等的学习

In [8]:
df = pd.DataFrame({
    "id":[1,2,3,4,5],
    "name":["a","b","c","d","e"],
    "age":[10,20,30,40,50]

},index=[1,2,3,4,5],columns=["name","id","age"])
print(df)

  name  id  age
1    a   1   10
2    b   2   20
3    c   3   30
4    d   4   40
5    e   5   50

In [19]:
#df的属性
print(df.columns)
print(df.index)
print(df.values)
print(df.ndim)
print(df.dtypes)
print(df.size)

Index(['name', 'id', 'age'], dtype='str')
Index([1, 2, 3, 4, 5], dtype='int64')
[['a' 1 10]
 ['b' 2 20]
 ['c' 3 30]
 ['d' 4 40]
 ['e' 5 50]]
2
name      str
id      int64
age     int64
dtype: object
15

In [21]:
print(df.T)

       1   2   3   4   5
name   a   b   c   d   e
id     1   2   3   4   5
age   10  20  30  40  50

In [31]:
print(df.loc[4])
print(df.loc[:,'name'])
print(df.at[3,'id'])
df.replace(40,41)

name     d
id       4
age     40
Name: 4, dtype: object
1    a
2    b
3    c
4    d
5    e
Name: name, dtype: str
3

  name  id  age
1    a   1   10
2    b   2   20
3    c   3   30
4    d   4   41
5    e   5   50

In [44]:
print(df.sort_values(by=['age','id'],ascending=[True,False]))

  name  id  age
1    a   1   10
2    b   2   20
3    c   3   30
4    d   4   40
5    e   5   50

#数据分析，导入导出

In [50]:
df = pd.read_csv('pandas_import_data/sales_basic.csv')#导入
print(df)
df = df.head(3)
df.to_csv('pandas_import_data/new.csv')

         date       city   product  units  price
0  2026-07-01   Shanghai  keyboard     12    199
1  2026-07-01    Beijing     mouse     20     89
2  2026-07-02  Guangzhou   monitor      5    899
3  2026-07-02   Shenzhen  keyboard      8    199
4  2026-07-03   Shanghai     mouse     15     89
5  2026-07-03    Beijing   monitor      3    899

In [57]:
#json
df2 = pd.read_json('pandas_import_data/products.json')
print(df2)
import json
with open('pandas_import_data/products.json') as f:
    products = json.load(f)

df3 =pd.DataFrame(df2['name'])
print(df3)

  product_id       name  category  price  stock
0       P001   keyboard  computer    199     45
1       P002      mouse  computer     89    120
2       P003    monitor  computer    899     18
3       P004  desk lamp    office    129     32
        name
0   keyboard
1      mouse
2    monitor
3  desk lamp

In [ ]:
#df.dropna(how = 'all')所有的值是确实值，才删除这一行
#df.dropna(thresh = 1) 如果至少有n个不是缺失值，就保留
#df.fillna(df[['~']].mean()使用统计值来填充
#df.ffill()用前面的值填充 bfill是用后面的

In [ ]:
#数据类型转换

In [63]:
df4 = pd.read_csv('pandas_import_data/type_conversion_practice.csv')#导入


df4['height_cm_int'] = df4['height_cm'].round().astype('Int64')
print(df4.dtypes)
#如果遇到字符串类型，最好用map（{}）做一个映射，映射为bool值

user_id            int64
name                 str
age                  str
height_cm        float64
signup_date          str
last_login           str
is_member            str
score                str
discount_rate        str
amount               str
city                 str
zip_code           int64
phone              int64
remarks              str
height_cm_int      Int64
dtype: object

In [ ]:
#数据变形 宽表转长表：melt   长转宽：pivot
#df[['']]= df['blood_pressure'].str.split('/',expand = Ture)

In [75]:
#数据分享
df5 =df4.head(2)

print(df5.T)

                                 0                    1
user_id                          1                    2
name                         Alice                  Bob
age                             18                   20
height_cm                    165.5                178.0
signup_date             2026-07-01           2026/07/02
last_login     2026-07-10 09:15:00  2026-07-10 18:30:00
is_member                      yes                   no
score                           92                   85
discount_rate                  10%                   0%
amount                    1,299.50               899.00
city                      Shanghai              Beijing
zip_code                      2101                 1002
phone                  13800000001          13800000002
remarks                     normal               normal
height_cm_int                  166                  178

In [77]:
#数据分箱
df1 = pd.DataFrame({
    'employee_id': [100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
    'salary': [24000, 17000, 17000, 9000, 6000, 4800, 4800, 4200, 12000, 9000]
})
df1

   employee_id  salary
0          100   24000
1          101   17000
2          102   17000
3          103    9000
4          104    6000
5          105    4800
6          106    4800
7          107    4200
8          108   12000
9          109    9000

In [78]:
pd.cut(df1['salary'], bins=[0,10000,20000,30000],labels=['low','mid','high']) #bins=n，分成n段区间，起始值、结束值是所有数据的最小值、最大值
#4200~14100~24000

0    high
1     mid
2     mid
3     low
4     low
5     low
6     low
7     low
8     mid
9     low
Name: salary, dtype: category
Categories (3, str): ['low' < 'mid' < 'high']

In [ ]:
#df.rename   .set_index .reset_index

时间戳

In [8]:
d = pd.Timestamp('2015-05-09 10:34')
print(d)
print(d.year)
print(d.month)
print(d.day)
print(d.day_name())
#df['datetime'].dt.year才能把时间取出来
#重采样  resample("YE")按年重采样

2015-05-09 10:34:00
2015
5
9
Saturday

分组聚合

In [18]:
#df.groupby('分组的字段')[‘聚合的字段’].聚合函数()
df = pd.read_csv('pandas_import_data/type_conversion_practice.csv')
df.groupby('user_id').groups#查看分组
df.groupby('user_id').get_group(2)

,user_id,name,age,height_cm,signup_date,last_login,is_member,score,discount_rate,amount,city,zip_code,phone,remarks
1,2,Bob,20,178.0,2026/07/02,2026-07-10 18:30:00,no,85,0%,899.00,Beijing,1002,13800000002,normal

In [ ]:
#关于数据清洗，首先要检查确实值   df.isna().sum()  df.dropna(inplace = Ture) 再用astype
#再构造数据特征  再把数据分箱
#df.groupby(['sex','island']).agg)=({          })
#.agg是对一个和多个数据进行操作